title: "[Zaulao]"
description: "[Zaulao]"
baseurl: "" # the subpath of your site, e.g. /blog
domain: "zaulao.com"
url: "https://zaulao.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: Zaulao 
github_username: Zaulao

#theme: jekyll-theme-console
remote_theme: b2a3e8/jekyll-theme-console

favicon: "favicon.ico"
header_pages:
  - index.md
  - about.md

style: dark # dark (default), light, nord or hacker
listen_for_clients_preferred_style: false # false (default) or true

permalink: /:title
show_dir_listing: false
footer: 'follow me on <a href="https://twitter.com/Zaulao">twitter</a>'
markdown: kramdown